set search_path=tpch;
select count(*) from lineitem;
select count(*) from customer;
select count(*) from nation;
select count(*) from orders;
select count(*) from part;
select count(*) from partsupp;
select count(*) from region;
select count(*) from supplier;
select count(*) from lineitem;
